# 1.两数之和
[table1]
expected = [[0, 1], [1, 2], [0, 1]]
nums = [[2, 7, 11, 15], [3, 2, 4], [3, 3]]
target = [9, 6, 6]

# 2.两数相加
[table2]
expected = [[7, 0, 8], [0], [8, 9, 9, 9, 0, 0, 0, 1]]
nums1 = [[2, 4, 3], [0], [9, 9, 9, 9, 9, 9, 9]]
nums2 = [[5, 6, 4], [0], [9, 9, 9, 9]]

# 3.无重复字符的最长子串
[table3]
expected = [3, 1, 3]
s = ["abcabcbb", "bbbbb", "pwwkew"]
